### ISSUE TITLE
Genus 2 curve stats

### ISSUE THREAD

**Issue by roed314** [roed314/lmfdb_postgres#21]
http://localhost:37777/Genus2Curve/Q/stats

The stats just need to be computed (they were in the postgres 9 database and just need to be regenerated)

**Comment by edgarcosta** [comment]
```
[2018-07-17 20:01:09 UTC] 500 error on URL http://legendre.mit.edu/Genus2Curve/Q/stats ('Database does not contain stats for num_rat_pts',)
Exception on /Genus2Curve/Q/stats [GET]
Traceback (most recent call last):
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/genus2_curves/main.py", line 123, in statistics
    info = { 'counts': g2cstats().counts(), 'stats': g2cstats().stats() }
  File "sage/misc/cachefunc.pyx", line 2377, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__ (build/cythonized/sage/misc/cachefunc.c:13430)
    self.cache = f(self._instance)
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/genus2_curves/main.py", line 377, in stats
    count_key='curves')
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/db_backend.py", line 2369, in display_data
    total, avg = self._get_total_avg(cols, constraint, include_avg)
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/db_backend.py", line 2323, in _get_total_avg
    raise ValueError("Database does not contain stats for %s"%(cols[0],))
ValueError: Database does not contain stats for num_rat_pts
[2018-07-17 20:01:21 UTC] 500 error on URL http://postgres.lmfdb.xyz/Genus2Curve/Q/stats ('Database does not contain stats for num_rat_pts',)
```

**Comment by roed314** [comment]
Fixed
