### ISSUE TITLE
small_gps conversion strings to LmfdbRealLiteral

### ISSUE THREAD

**Issue by edgarcosta** [roed314/lmfdb_postgres#29]
small_gps center many things of format A.B are taken as LmfdbRealLiteral instead of a pair of integers or str

**Comment by roed314** [comment]
I think I've fixed this.  Do you have a page I can test to make sure?

**Comment by edgarcosta** [comment]
I'm not aware of any broken page, at the moment.
Everywhere where I found this bug had an impact, I just casted the
LmfdbRealLiteral to a string, and everything worked as expected.

**Comment by edgarcosta** [comment]
I think this is related:
http://localhost:37777/SatoTateGroup/1.4.6.1.1a
or
http://postgres.lmfdb.xyz/SatoTateGroup/1.4.6.1.1a




```
[2018-07-18 17:28:23 UTC] 500 error on URL http://postgres.lmfdb.xyz/SatoTateGroup/1.4.6.1.1a ('operator does not exist: text = numeric\nLINE 1: ... "order", "clases" FROM "gps_small" WHERE "label" = 1.1 ORDE...\n                                                             ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n',)
Exception on /SatoTateGroup/1.4.6.1.1a [GET]
Traceback (most recent call last):
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-8.2/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/sato_tate_groups/main.py", line 138, in by_label
    return search_by_label(label)
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/sato_tate_groups/main.py", line 148, in search_by_label
    return render_by_label(label)
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/sato_tate_groups/main.py", line 323, in render_by_label
    G = db.gps_small.lookup(data['component_group'])
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/db_backend.py", line 861, in lookup
    return self.lucky({self._label_col:label}, projection=projection)
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/db_backend.py", line 710, in lucky
    cur = self._execute(selecter, values)
  File "/home/lmfdb/lmfdb-git-postgres/lmfdb/db_backend.py", line 155, in _execute
    cur.execute(query, values)
ProgrammingError: operator does not exist: text = numeric
LINE 1: ... "order", "clases" FROM "gps_small" WHERE "label" = 1.1 ORDE...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

[2018-07-18 17:28:26 UTC] 500 error on URL http://postgres.lmfdb.xyz/SatoTateGroup/1.4.6.1.1a ('operator does not exist: text = numeric\nLINE 1: ... "order", "clases" FROM "gps_small" WHERE "label" = 1.1 ORDE...\n                                                             ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n',)
```

**Comment by roed314** [comment]
I fixed this as well.
