### ISSUE TITLE
InterfaceError

### ISSUE THREAD

**Issue by edgarcosta** [roed314/lmfdb_postgres#84]
Sometimes the connection doesn't get reseted, and `InterfaceError` is raised: 
```
Exception on /Genus2Curve/Q/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-8.3/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/genus2_curves/main.py", line 96, in index_Q
    return genus2_curve_search(to_dict(request.args))
  File "/home/lmfdb/lmfdb-git-web/lmfdb/genus2_curves/main.py", line 299, in genus2_curve_search
    res = db.g2c_curves.search(query, ['label','eqn','st_group','is_gl2_type','is_simple_geom','analytic_rank'], limit=count, offset=start, info=info)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/db_backend.py", line 879, in search
    nres = self.stats.quick_count(query)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/db_backend.py", line 2361, in quick_count
    cur = self._execute(selecter, [cols, vals])
  File "/home/lmfdb/lmfdb-git-web/lmfdb/db_backend.py", line 195, in _execute
    cur = self.conn.cursor()
InterfaceError: connection already closed
[2018-08-21 22:04:38 UTC] 500 error on URL http://prodweb1.lmfdb.xyz/Genus2Curve/Q/?abs_disc=1-499 ('connection already closed',)
```

**Comment by roed314** [comment]
So the change I suggested worked?

**Comment by edgarcosta** [comment]
Yes! That, and moving the line 
```
cur = self.conn.cursor()
```
inside of the `try` block, as that was the line raising the exception.

**Comment by roed314** [comment]
Great!
